# .zsh.d/zshenv
# https://github.com/clear-code/zsh.d/blob/master/zshenv

# for sudo
typeset -xT SUDO_PATH sudo_path
typeset -U sudo_path
sudo_path=({,/usr/local,/usr}/sbin(N-/))

# less
export LESS='--RAW-CONTROL-CHARS'
export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh %s'

# EMAIL
email_files=(~/.zsh.d/email(N-.)
             ~/.email(N-.))
for email_file in ${email_files}; do
  export EMAIL=$(cat "$email_file")
  break
done
