[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  if (&t_Co ==# 256) && !has('gui_running')
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=233
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=232
  endif

'''

[[plugins]]
repo = 'tpope/vim-surround'
# Ruby http://d.hatena.ne.jp/ursm/20080402/1207150539
hook_add = '''
  let g:surround_{char2nr('%')} = "%(\r)"
  let g:surround_{char2nr('w')} = "%w(\r)"
  let g:surround_{char2nr('#')} = "#{\r}"
  let g:surround_{char2nr('e')} = "begin \r end"
  let g:surround_{char2nr('i')} = "if \1if\1 \r end"
  let g:surround_{char2nr('u')} = "unless \1unless\1 \r end"
  let g:surround_{char2nr('c')} = "class \1class\1 \r end"
  let g:surround_{char2nr('m')} = "module \1module\1 \r end"
  let g:surround_{char2nr('d')} = "def \1def\1\2args\r..*\r(&)\2 \r end"
  let g:surround_{char2nr('p')} = "\1method\1 do \2args\r..*\r|&| \2\r end"
  let g:surround_{char2nr('P')} = "\1method\1 {\2args\r..*\r|&|\2 \r }"
'''

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'rizzatti/dash.vim'
hook_source = 'nmap <silent> <Leader>d <Plug>DashSearch'

[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'tpope/vim-rails'
